# List of cryptocurrencies to monitor
cryptocurrencies:
  - bitcoin      # Bitcoin
  - ethereum     # Ethereum
  - tether       # Tether
  - binancecoin  # Binance Coin
  - usd-coin     # USD Coin
  - ripple       # XRP
  - solana       # Solana
  - cardano      # Cardano
  - dogecoin     # Dogecoin
  - tron         # TRON

# Auto-refresh interval in seconds (default: 180 seconds = 3 minutes)
refresh_interval: 180
